### ISSUE TITLE
resize pip to cover special view

### ISSUE THREAD

**Issue by fukemy** [nexor-it/PIPWKit#6]
hi. i have a videoplayer in PIPUsable, i want when enter PIP mode, the pip will cover the video, how can i do this? Thanks

**Comment by gali8** [comment]
Did you try setting pipSize and initialPosition?

**Comment by fukemy** [comment]
Thanks buddy, it's work with autolayout

**Comment by fukemy** [comment]
hi, can i ask the question?

 Below is my table layout, i want to pip cover the mid view only


![Simulator Screen Shot - iPhone 11 - 2021-06-28 at 22 41 46](https://user-images.githubusercontent.com/8202437/123665150-32773580-d862-11eb-9400-b02caaa3cce3.png)

I have set the pipSize equal to center frame, but when enter pip mode, i got wrong view like below image

![simulator_screenshot_13F2DE47-7D45-454C-B4EB-F4D235D6AA33](https://user-images.githubusercontent.com/8202437/123665383-6d796900-d862-11eb-9938-b9383533808e.png)

here is my code:
```
if !PIPKit.isPIP {
            self.navigationController?.setNavigationBarHidden(true, animated: true)
            var viewMatched = mainList[0]
            if let mainLayoutOrder = mainLayoutOrder{
                viewMatched = mainList[mainLayoutOrder - 1] // -> this is center view
            }
            (parent as! PIPNavigationController).pipSize = viewMatched.frame.size
            (parent as! PIPNavigationController).startPIPMode()
            onMiximize?()
        }
```
it's seem the pipView only cover from x = 0 and y = 0. So if i want to cover only mid view, or another specific view, can u give me some advices to do this? Thanks

**Comment by fukemy** [comment]
i changed to auto layout but it still not working
```
let items = AppUtils.getListItemsForGroupLayout(layoutCode)
        for i in 0..<items.count{
            let span = items[i]
            
            let spanWidth = span[0]
            let spanHeight = span[1]
            let spanX = span[2]
            let spanY = span[3]
            
            let x = minWidth * spanX
            let y = minHeight * spanY
            
            let v = UIView(frame: .zero)
            v.backgroundColor = .random()
            view.addSubview(v)
            
            v.snp.makeConstraints { make in
                make.leading.equalToSuperview().inset(x)
                make.top.equalToSuperview().inset(y)
                make.width.equalTo(minWidth * spanWidth)
                make.height.equalTo(minHeight * spanHeight)
            }
            
            addClickToMaximizePIP(v)
            mainList.append(v)
        }
```

**Comment by fukemy** [comment]
ok fixed it
